### PR TITLE
Improve test output messages for TestClassifier_WithinConfidenceThres…

### PR DESCRIPTION
**Pull request by dsymonds**
…hold.

This will hopefully help us diagnose the Travis failures.

### CODE REVIEW

**Comment by dsymonds** [comment]
And wouldn't you know it? The Travis run for this pull request gave green across the board. Sigh.

**Comment by gwelymernans** [comment]
Yeah, I noticed that. Maybe it was a bug in Go 1.8 that got fixed (either intentionally or by accident)?

**Comment by dsymonds** [comment]
No, it's not some weird Go 1.8 thing. It's simply inconsistent and it sometimes fails and sometimes passes on other versions too. I'd be more likely to blame the Travis environment.

**Comment by dsymonds** [comment]
This might still be worth merging.

**Pull request merged**
